/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as TrackedRouteImport } from "./routes/tracked";
import { Route as SyncRouteImport } from "./routes/sync";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as LogRouteImport } from "./routes/log";
import { Route as DiscoverRouteImport } from "./routes/discover";
import { Route as AboutRouteImport } from "./routes/about";
import { Route as IndexRouteImport } from "./routes/index";

const TrackedRoute = TrackedRouteImport.update({
  id: "/tracked",
  path: "/tracked",
  getParentRoute: () => rootRouteImport,
} as any);
const SyncRoute = SyncRouteImport.update({
  id: "/sync",
  path: "/sync",
  getParentRoute: () => rootRouteImport,
} as any);
const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const LogRoute = LogRouteImport.update({
  id: "/log",
  path: "/log",
  getParentRoute: () => rootRouteImport,
} as any);
const DiscoverRoute = DiscoverRouteImport.update({
  id: "/discover",
  path: "/discover",
  getParentRoute: () => rootRouteImport,
} as any);
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/discover": typeof DiscoverRoute;
  "/log": typeof LogRoute;
  "/settings": typeof SettingsRoute;
  "/sync": typeof SyncRoute;
  "/tracked": typeof TrackedRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/discover": typeof DiscoverRoute;
  "/log": typeof LogRoute;
  "/settings": typeof SettingsRoute;
  "/sync": typeof SyncRoute;
  "/tracked": typeof TrackedRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/about": typeof AboutRoute;
  "/discover": typeof DiscoverRoute;
  "/log": typeof LogRoute;
  "/settings": typeof SettingsRoute;
  "/sync": typeof SyncRoute;
  "/tracked": typeof TrackedRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths: "/" | "/about" | "/discover" | "/log" | "/settings" | "/sync" | "/tracked";
  fileRoutesByTo: FileRoutesByTo;
  to: "/" | "/about" | "/discover" | "/log" | "/settings" | "/sync" | "/tracked";
  id: "__root__" | "/" | "/about" | "/discover" | "/log" | "/settings" | "/sync" | "/tracked";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AboutRoute: typeof AboutRoute;
  DiscoverRoute: typeof DiscoverRoute;
  LogRoute: typeof LogRoute;
  SettingsRoute: typeof SettingsRoute;
  SyncRoute: typeof SyncRoute;
  TrackedRoute: typeof TrackedRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/tracked": {
      id: "/tracked";
      path: "/tracked";
      fullPath: "/tracked";
      preLoaderRoute: typeof TrackedRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/sync": {
      id: "/sync";
      path: "/sync";
      fullPath: "/sync";
      preLoaderRoute: typeof SyncRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/log": {
      id: "/log";
      path: "/log";
      fullPath: "/log";
      preLoaderRoute: typeof LogRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/discover": {
      id: "/discover";
      path: "/discover";
      fullPath: "/discover";
      preLoaderRoute: typeof DiscoverRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/about": {
      id: "/about";
      path: "/about";
      fullPath: "/about";
      preLoaderRoute: typeof AboutRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DiscoverRoute: DiscoverRoute,
  LogRoute: LogRoute,
  SettingsRoute: SettingsRoute,
  SyncRoute: SyncRoute,
  TrackedRoute: TrackedRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
